### ISSUE TITLE
Hapara filter has locked me out of signing into GitHub

### ISSUE THREAD

**Issue by m1kecraft** [xlak/sturdy-potato#6]
I can't sign into GitHub on my school Chromebook, and it also has this "real time analysis game detection" which blocks games while you are playing them.  Same for proxies.  I am trying to figure out how to get the source code for the extension.  This is because there is something called "support commands" which might be a bypass, and I don't know how to use it.

**Comment by petm5** [comment]
That would be Hapara Filter I believe. It can detect key presses associated with games to block them. The "support commands" unfortunately need to be signed with a private key held by the Hapara developers to be accepted, so you can't do anything interesting with those (yet). Its also really hard to bypass because of its AI-based detection (which probably makes school chromebooks a lot slower than they already are), but it can still be done. Proxies like nebula might work if you turn on cloaking really quickly before the AI analysis kicks in.

Does the chaos exploit by xlak work? You should also look into the sh1mmer exploit (It lets you fully bypass enterprise enrollment on many chromebook models without disassembling it or using an external programmer.) You may have to downgrade the Chrome OS version back to v110 first with a recovery USB before the exploit will succeed.

**Comment by m1kecraft** [comment]
Chaos exploit does not work due to inspect blocked.  Also, where can I find the sh1mmer exploit?

**Comment by petm5** [comment]
[Here](https://sh1mmer.me/).

**Comment by m1kecraft** [comment]
ok thanks

**Comment by m1kecraft** [comment]
How do I get an RMA shim for Sarien, which is my device?
